site_name: Red Hat Enterprise Linux Image Mode demo
repo_url: https://github.com/redhat-cop/redhat-image-mode-demo/
edit_uri: blob/main/
site_author: Alessandro Rossi - Red Hat
site_description: Documentation page for the Red Hat Enterprise Linux (RHEL) Image mode demo hosted on GitHub.
theme:
  name: material
  favicon: assets/logo.png
  logo: assets/logo.png
  font:
    text: Red Hat Display
  features:
    - content.code.copy
    - navigation.expand
    - content.tooltips
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Getting Started:
    - Introducing RHEL Image mode: getting-started/introduction.md
    - Quickstart: getting-started/quickstart.md
    - Contributing to the project: getting-started/contributing.md
  - Use Cases:
    - Build a simple RHEL container: use-cases/bootc-container-simple/README.md
    - Build an Apache RHEL image: use-cases/bootc-container-httpd/README.md
    - Use a RHEL bootc container to spin up a RHEL 10 VM with Anaconda and Kickstart: use-cases/bootc-container-anaconda-ks/README.md
    - Update a VM based on a RHEL bootc container as a source adding packages and configuration: use-cases/bootc-container-update/README.md
    - Upgrade a VM based on RHEL 10.0 bootc container to RHEL 10 Beta: use-cases/bootc-container-upgrade/README.md
    - Apply a different RHEL container image to an existing VM: use-cases/bootc-container-replace/README.md
    - Generate a RHEL QCOW image for a VM using bootc-image-builder: use-cases/bootc-image-builder-qcow/README.md
    - Generate a RHEL ISO image for a VM using bootc-image-builder: use-cases/bootc-image-builder-iso/README.md
    - Generate a RHEL AMI image for an AWS instance using bootc-image-builder: use-cases/bootc-image-builder-ami/README.md
    - Manage RHEL Image Mode systems with Red Hat Insights: use-cases/image-mode-management-insights/README.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: !relative $config_dir
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji
  - abbr
plugins:
  - macros
